#!/usr/bin/env zsh

for list_index in {1..4}; do
    list_image=list-$list_index.png
    (( count = $(identify -format %h $list_image) / 64 ))
    for index in {0..$(( count - 1 ))}; do
        convert $list_image -crop 64x64+0+$(( 64 * $index )) +repage m.weibo.cn-$list_index-$index.png
    done
done
